### ISSUE TITLE
How do you exclude third party roles in requirements.yml

### ISSUE THREAD

**Issue by dcw329** [ansible/ansible-lint#541] opened 2019-06-19 01:06 UTC
How do you exclude a third party roles, or any role for that matter. I have tried

I have tried
```exclude_paths:
  - ./roles/nexus
  - requirements.yml
  - compliance-playbook.yml
  - RHEL7-CIS
  - ./roles/RHEL7-CIS
  - ./.ansible/roles/RHEL7-CIS
  - ~/.ansible/roles/RHEL7-CIS
  - hardened-core.yml
  - site.yml
  - meta
  - ./roles/java```

I just want to exclude RHEL7-CIS and nothing seems to prevent it from running. I have even excluded files referencing it. I am running this as a pre-commit run -a with an exclude: .*RHEL.* even. I can not get RHEL7-CIS to stop being checked. And even some of the roles i have excluded like java continue to have files picked up.

**Comment by Moumoutaru** [comment] 2019-07-02 12:59
Yea, I am running into this as well, trying to throw this into CI and running into the situation where each playbook book is checking associated roles. Was hoping to lint them separately.

**Comment by Moumoutaru** [comment] 2019-07-02 13:04
This seems to be a dupe of https://github.com/ansible/ansible-lint/issues/322

**Closed** 2020-02-27 17:11 UTC
