### ISSUE TITLE
[Feature Idea] order of options in task

### ISSUE THREAD

**Issue by freeseacher** [ansible/ansible-lint#828] opened 2020-06-13 22:17 UTC
##### Summary
Add lint and probably autofix for order of options in task. 
On several review i've found that people sometimes use name in the middle of task definition. Adding something like 
```
- name:
- action:
- other_stuff
- where
```
Or any other order will be appriciated 
Maybe similar for play 
```
- name: 
- hosts:
- some_other_stuff
- tasks_pre:
- roles:
- post_tasks:
```
and so on 

##### Issue Type

- Feature Idea

##### Additional Information

```console

```

**Comment by ssbarnea** [comment] 2020-06-14 07:46
I do fully agree with you but there is more complexity to that issue that you may think. This task is a duplicate of https://github.com/ansible/ansible-lint/issues/578 -- lets continue there, maybe we can find an initial set of sorting rules we can agree on.

**Closed by ssbarnea** 2020-06-14 07:46 UTC
Labels: priority/medium, status/new
