### ISSUE TITLE
6.9.1 will not install on anything but Python 3.11

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible-lint#2808] opened 2022-12-10 22:26 UTC
##### Summary

I would like to clarify if ansible-lint is making Python 3.11 a hard requirement.

```
$ poetry install
  The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - will-not-work-on-windows-try-from-wsl-instead requires Python >=3.11,<4.0, so it will not be satisfied for Python >=3.10,<3.11
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

Fedora 36
Python 3.10.8
ansible-lint 6.9.1

- ansible installation method: pip/poetry
- ansible-lint installation method: pip/poetry

##### STEPS TO REPRODUCE

```
$ cat pyproject.toml
[tool.poetry]
name = "myproject"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
ansible-lint = "^6.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


$ poetry install
Creating virtualenv myproject-tYPnKevq-py3.10 in /home/user/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.9s)

  SolverProblemError

  The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - will-not-work-on-windows-try-from-wsl-instead requires Python >=3.11,<4.0, so it will not be satisfied for Python >=3.10,<3.11

  Because no versions of ansible-lint match >6.9.1,<7.0.0
   and ansible-lint (6.9.1) depends on will-not-work-on-windows-try-from-wsl-instead (*), ansible-lint (>=6.9.1,<7.0.0) requires will-not-work-on-windows-try-from-wsl-instead (*).
  Because will-not-work-on-windows-try-from-wsl-instead (0.1.0) requires Python >=3.11,<4.0
   and no versions of will-not-work-on-windows-try-from-wsl-instead match !=0.1.0, will-not-work-on-windows-try-from-wsl-instead is forbidden.
  Thus, ansible-lint is forbidden.
  So, because myproject depends on ansible-lint (^6.9.1), version solving failed.

  at /usr/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For will-not-work-on-windows-try-from-wsl-instead, a possible solution would be to set the `python` property to ">=3.11,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by ssbarnea** [comment] 2022-12-11 12:22
Duplicate of https://github.com/ansible/ansible-lint/issues/2795

**Closed by ssbarnea** 2022-12-11 12:22 UTC
Labels: new, bug
