### ISSUE TITLE
jinja[spacing] suggestion doesn't cope well with multi-line code

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible-lint#2313] opened 2022-08-22 12:52 UTC
##### Summary

When a Jinja expression spans multiple lines, the suggested change in the `ansible-lint` output is only displaying the last line.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
% ansible --version
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/evgeni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/a/venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/evgeni/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/a/venv/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.1.2
  libyaml = True


% ansible-lint --version
ansible-lint 6.5.0 using ansible 2.13.3
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Fedora 36, but irrelevant

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  vars:
    a: true
    b: false
  tasks:
    - name: Print stuff
      ansible.builtin.debug:
        msg: "{{ [
            a | ternary('Red Hat Enterprise Linux Server', ''),
            b | ternary('Red Hat Enterprise Linux for x86_64', '')
          ] | select() | list }}"
```

```console (paste below)
% ansible-lint lol.yml   
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: lol.yml
WARNING  Listing 1 violation(s) that are fatal
jinja: Jinja2 spacing could be improved: {{ [ a | ternary('Red Hat Enterprise Linux Server', ''), b | ternary('Red Hat Enterprise Linux for x86_64', '') ] | select() | list }} -> {{ [a | ternary('Red Hat Enterprise Linux Server', ''), b | ternary('Red Hat Enterprise Linux for x86_64', '')] | select() | list }} (jinja[spacing])
lol.yml:7 Jinja2 template rewrite recommendation: `{{  | select() | list }}`.

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - jinja[spacing]  # Rule that looks inside jinja2 templates.

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

##### Desired Behavior

The "rewrite recommendation" should contain the "correct" recommendation ;-)

##### Actual Behavior

See reproducer above.

Interestingly, the "jinja" prefixed line has the correct changes reported, but not the "lol.yml:7" one, so the data is getting lost somewhere in the reporting stack?

**Comment by evgeni** [comment] 2022-08-22 12:57
FTR, changing the playbook to read:
```
        msg: "{{ [a | ternary('Red Hat Enterprise Linux Server', ''),
            b | ternary('Red Hat Enterprise Linux for x86_64', '')]
            | select() | list }}"
```

makes lint happy

**Comment by ssbarnea** [comment] 2022-08-24 14:18
I am closing this because I was not able to reproduce it but please, if you can find a way to reproduce from the command line send me a link to gist.

**Closed by ssbarnea** 2022-08-24 14:18 UTC
Labels: bug

**Comment by evgeni** [comment] 2022-08-24 15:13
```console
% pip freeze
ansible-compat==2.2.0
ansible-core==2.13.3
ansible-lint==6.5.0
attrs==22.1.0
bracex==2.3.post1
cffi==1.15.1
commonmark==0.9.1
cryptography==37.0.4
enrich==1.2.7
filelock==3.8.0
iniconfig==1.1.1
Jinja2==3.1.2
jsonschema==4.14.0
MarkupSafe==2.1.1
packaging==21.3
pathspec==0.9.0
pluggy==1.0.0
py==1.11.0
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.18.1
pytest==7.1.2
PyYAML==6.0
resolvelib==0.8.1
rich==12.5.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
subprocess-tee==0.3.5
tomli==2.0.1
wcmatch==8.4
yamllint==1.27.1
```

this is what I have installed in the venv where the above pastes are from.

**Comment by evgeni** [comment] 2022-08-26 06:15
This is still present in 6.5.1.

Additionally, it now wants to edit the code to read:
```
        msg: "{{ [a |ternary('Red Hat Enterprise Linux Server', ''),
            b |ternary('Red Hat Enterprise Linux for x86_64', '')]
            | select() | list }}"
```

(note the missing space before the `ternary`) which I think is wrong? Yes, it is a jinja expressin *inside* a list, which is probably rather uncommon, but still.
