### ISSUE TITLE
When running a lint from a collection that has import_playbook to same collection you get errors.

### ISSUE THREAD

**Issue by provenvelocity** [ansible/ansible-lint#1641] opened 2021-06-24 19:58 UTC
##### Summary
When you run ansible-lint from a collection that has a playbook that imports from the current collection you get an error in the way you build the list of files by adding a playbook that does not exist except in a collection. 

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```
ansible-lint --version
ansible [core 2.11.1] 
  config file = None
  configured module search path = ['/Users/H217689/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/H217689/.pv_devops/pv_devops_venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/H217689/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/H217689/.pv_devops/pv_devops_venv/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
ansible-lint 5.0.12 using ansible 2.11.1

```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

##### OS / ENVIRONMENT
Any

##### STEPS TO REPRODUCE

```console (paste below)
Create a collection
add a dependency
then make a playbook that implements the dependency
then make a test in a test folder that imports-playboox made above and you 
then run ansible-lint it will error out

This link has a full write-up with examples and ways to reproduce. 

https://github.com/provenvelocity/devops_test/tree/Collections_issue
```

##### Desired Behaviour

Lint should complete successfully

##### Actual Behaviour
This link has a full write-up with examples and ways to reproduce. 

https://github.com/provenvelocity/devops_test/tree/Collections_issue

I have the code needed to fix this issue and will be branching and linking to it shortly.

**Comment by erikgb** [comment] 2021-08-05 20:07
I was about to report a new issue, but then found this, and I think I have the same problem. 😺 

But I have created a [much simpler GH project](https://github.com/erikgb/ansible_lint_issue) to reproduce the bug (or missing feature) in ansible-lint.

### To reproduce

1. `git clone https://github.com/erikgb/ansible_lint_issue.git ansible_collections/erikgb/ansible_lint_issue`
2. `cd ansible_collections/erikgb/ansible_lint_issue/`
3. `molecule test` # successful
4. `ansible-lint` # fails

The error message from ansible-lint:

````shell
D:/tmp/ansible_collections/erikgb/ansible_lint_issue (m) $ ansible-lint
WARNING  Listing 1 violation(s) that are fatal
load-failure: [Errno 2] No such file or directory: 'molecule/erikgb.ansible_lint_issue.debug' (filenotfounderror)
molecule/erikgb.ansible_lint_issue.debug:1

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - load-failure  # Failed to load or parse file

Finished with 1 failure(s), 0 warning(s) on 7 files.
D:/tmp/ansible_collections/erikgb/ansible_lint_issue (m) $
````

So molecule supports testing playbooks from collections, but ansible-lint doesn't!?!

And in the molecule doc's this is even documented as a unsupported DIY solution for testing collections: https://molecule.readthedocs.io/en/latest/faq.html#can-i-test-ansible-collections-with-molecule

I know there might be something in the works, but is it possible to hack in a temporary solution?

**Comment by provenvelocity** [comment] 2021-08-05 20:12
If you would like you can use my fork it fixed all the issues for me

**Comment by erikgb** [comment] 2022-02-18 23:03
@ssbarnea, any prospects for this error to be fixed? Collections has been around in Ansible for some time now, and ansible-lint does not yet support it? 🤔

**Comment by provenvelocity** [comment] 2022-02-18 23:12
It’s fixed in my code I just moved on to another project after all the
issues getting it landed… if someone wants to take my pull over I don’t
care… the fixes are small and surgacle

**Comment by ssbarnea** [comment] 2022-02-19 08:31
I am more than happy to merge a fix but we need one that passes CI and has a regression test.

**Comment by provenvelocity** [comment] 2022-02-20 22:54
:) let me see what I can do

**Comment by ssbarnea** [comment] 2022-03-18 13:58
@provenvelocity Can you check if you can reproduce the bug with 6.0.1 ? I made change that fix it, almost for sure. If so, please close it.

**Comment by erikgb** [comment] 2022-03-22 09:48
@ssbarnea I just tested this with 6.0.1, and it seems to work! Well done, thanks! ❤️ But maybe @provenvelocity should verify the fix as well - before closing this issue?

**Comment by provenvelocity** [comment] 2022-03-22 17:56
I plan to during my lunch today thanks!

**Comment by ssbarnea** [comment] 2023-05-12 09:16
I tested manually and I was not able to reproduce this bug with current version of the linter. It was able to correctly find the playbook and also to raise an error if it did not. Keep in mind that it needs to look like:

```
- name: Import other playbooks from same collection
  import_playbook: community.molecule.validate # <-- playbooks/validate.yml being the effective file
```

**Closed by ssbarnea** 2023-05-12 09:16 UTC
Labels: bug
