### ISSUE TITLE
Crash on indexing empty cmd arguments

### ISSUE THREAD

**Issue by danielhoherd** [ansible/ansible-lint#391] opened 2018-11-01 21:38 UTC
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/daniel.hoherd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Users/daniel.hoherd/Library/Python/3.7/bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:13:13) [Clang 9.1.0 (clang-902.0.39.2)]
$ ansible-lint --version
ansible-lint 3.5.1
```

- ansible installation method: pip3 version 18.1 (python 3.7)
- ansible-lint installation method: pip3 version 18.1 (python 3.7)

# Desired Behavior

`ansible-lint` does not die with a python stack trace when run on invalid ansible code.

# Actual Behavior (Bug report only)

## playbook.yml
```
---
- name: Converge
  hosts: all
  gather_facts: no
  roles:
    - role: foo
```
## roles/foo/tasks/main.yml
```
---
- name: Test a command
  command:
    command: ls
    chdir: /
```

## ansible-playbook -i 'localhost,' playbook.yml

```
$ ansible-playbook -i 'localhost,' playbook.yml
PLAY [Converge] ***********************************************************

TASK [foo : Test a command] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (command) module: command Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, warn"}
	to retry, use: --limit @/Users/daniel.hoherd/temp/2018-11-01/playbook.retry

PLAY RECAP ****************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

## ansible-lint playbook.yml
```
$ ansible-lint playbook.yml
Traceback (most recent call last):
  File "/Users/daniel.hoherd/Library/Python/3.7/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansiblelint/__main__.py", line 176, in main
    matches.extend(runner.run())
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansiblelint/__init__.py", line 243, in run
    skip_list=self.skip_list))
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansiblelint/__init__.py", line 70, in matchtasks
    result = self.matchtask(file, task)
  File "/Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py", line 54, in matchtask
    first_cmd_arg = task["action"]["__ansible_arguments__"][0]
IndexError: list index out of range
```

**Comment by aknrdureegaesr** [comment] 2018-11-08 16:24
I have this problem also. It first occurred at a slightly different place:

```
Traceback (most recent call last):
  File "/home/andreask/workspace-iQpi/virtualenv/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/home/andreask/workspace-iQpi/virtualenv/lib/python3.5/site-packages/ansiblelint/__main__.py", line 176, in main
    matches.extend(runner.run())
  File "/home/andreask/workspace-iQpi/virtualenv/lib/python3.5/site-packages/ansiblelint/__init__.py", line 243, in run
    skip_list=self.skip_list))
  File "/home/andreask/workspace-iQpi/virtualenv/lib/python3.5/site-packages/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/andreask/workspace-iQpi/virtualenv/lib/python3.5/site-packages/ansiblelint/__init__.py", line 70, in matchtasks
    result = self.matchtask(file, task)
  File "/home/andreask/workspace-iQpi/virtualenv/lib/python3.5/site-packages/ansiblelint/rules/EnvVarsInCommandRule.py", line 41, in matchtask
    first_cmd_arg = task['action']['__ansible_arguments__'][0]
```

This bug can be reproduced with a very simple playbook:

```
# This playbook demonstrates a bug in ansible-lint

- name: Demonstrate ansible-lint bug
  hosts: localhost

  tasks:
    - name: Bugdemo
      command:
        argv:
          - /bin/echo
          - Hello
          - World
```
I included a print statement into `EnvVarsInCommandRule.py`, here is the resulting object it is using:

```
{
  '__file__': 'ansible-lint-bug.yml',
  'delegate_to': None,
  '__line__': 7,
  'name': 'Bugdemo',
  'action': {
    '__ansible_arguments__': [],
    'argv': [
      '/bin/echo',
      'Hello',
      'World'],
    '__line__': 9,
    '__ansible_module__': 'command',
    '__file__': 'ansible-lint-bug.yml'},
  '__ansible_action_type__': 'task'}
```
The code that's running is `task["action"]["__ansible_arguments__"][0]`.

I speculate it should be `task["action"]["argv"][0]`.

Changing it accordingly makes that bug disappear, but now I have the original problem at 

`CommandsInsteadOfArgumentsRule.py", line 54, in matchtask
    first_cmd_arg = task["action"]["__ansible_arguments__"][0]`

Changing that, it reappears in

`"/home/andreask/workspace-iQpi/virtualenv/lib/python3.5/site-packages/ansiblelint/rules/CommandsInsteadOfModulesRule.py", line 57, in matchtask
    first_cmd_arg = task["action"]["__ansible_arguments__"][0]`

**Comment by aknrdureegaesr** [comment] 2018-11-08 16:43
I think this bug is a duplicate of #352.

**Closed** 2019-02-04 15:42 UTC
