### ISSUE TITLE
no-shorthand: Disallow `=` style argument defintion

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2117] opened 2022-05-10 12:17 UTC
As an opt in rule until profile support is available we should disallow yaml ignorant style argument definition for tasks:

e.g.

```
- debug: msg="END connection={{ ansible_connection }} nxos_linkagg sanity test"
```

Related #2116

**Comment by IPvSean** [comment] 2022-05-10 12:26
I like this idea, you can always turn it off.... but I am a fan of being more prescriptive / opinionated on this, and this confuses people new to Ansible

**Comment by MarkusTeufelberger** [comment] 2022-05-16 23:21
Duplicate of https://github.com/ansible/ansible-lint/discussions/1609

**Closed** 2022-10-01 09:34 UTC
Labels: new rule
